### PR TITLE
Removing Deprecated Util Functions

### PR DESCRIPTION
**Pull request by vigneshshanmugam**
Updated Examples which were using deprecated Util functions.

### CODE REVIEW

**Comment by jmaxxz** [comment]
@mranney as you have already made this changes in https://github.com/mranney/http_trace I recommend we opt for pull #147 and remove examples from this library.

@vigneshshanmugam thanks for the PR, if @mranney wants to keep examples in this repo will merge it in.

**Comment by vigneshshanmugam** [comment]
Sure @jmaxxz  :)

**Comment by mranney** [comment]
Yeah, let's clean out any examples that don't actually work, or at least fix the ones that do. It would be nice to give people some examples of what can be done, so feel free to add any other informative examples if you have some.

http_trace has been its own repo for a while, so it's good to see it removed.

**Comment by vigneshshanmugam** [comment]
Sure will raise a new request removing the http_trace.

**Pull request merged**
