### PR TITLE
Add probe support

### PR DESCRIPTION
**Pull request by jmaxxz**
Will merge in 20min, if there are no comments.

### CODE REVIEW

**Comment by fridaystreet** [comment]
Hi @jmaxxz,

Thanks for this, does it still extract the RSSI and mac address of the sending device or just the SSID?

Cheers
Paul

**Comment by jmaxxz** [comment]
@fridaystreet check the [radio frame](https://github.com/jmaxxz/node_pcap/blob/addProbeSupport/decode/ieee802.11/radio_frame.js) to see if it has what you want on it.

**Comment by fridaystreet** [comment]
Ahh yeah great thanks. Didn't realise it had a section collapsed.

Will try and test this asap. Thanks again for fixing it so quickly

**Comment by fridaystreet** [comment]
Hi Jmaxxz,

Sorry I haven't reported back in this. I've been having a bit of trouble
trying to get the updates installed. I originally installed from now, but I
assume that isn't up to date with these latest changes as I've tried doing
a reinstall and doesn't have the new files.

So I've tried installing from git, but I just get pcap not found. I've
tried adding the path to the cloned folder to node_path, but still no luck.

I'll keep playing around and once I get it working I'll let you know how
the wifi stuff goes

Cheers
Paul

**Comment by jmaxxz** [comment]
@fridaystreet if you want the bleeding edge you can link your project's copy of node_pcap to your local git clone.

Use the following to do that:
```bash
cd node_pcap
npm link #sudo maybe required
cd ../your_app
npm link pcap #sudo maybe required
```

More detailed help
http://browsenpm.org/help

**Comment by fridaystreet** [comment]
@jmaxxz this is working great thanks

**Comment by fridaystreet** [comment]
@jmaxxz sorry something still isn't quite right with this. It's definitely decoding the ieee802_11 frame correctly, but not the header.

If you looks at the output of the decoding below the headerLength, strength and antenna appear to be incorrect based on a comparison in wireshark. In wireshark the headers of probe request are always 25. This also lines up with looking at where the signal is pulled from at offset=23, noise is offset=24 and antenna is offset=25

The buffer itself appears to only have 18 bytes before it starts the probe request part of the frame. So in radiopacket once it gets passed  the //Flags offset += 2;  section (18 bytes) it's no longer reading the header and is reading from the probe request section, hence why it's incorrect.

So somewhere along the way the radiotap header is losing 7 bytes. I'll keep digging to see if I can track it down, but if you can shed any light on where this might be getting truncated it would be really appreciated.

Cheers
Paul

Buffer:
 <Buffer 00 00 12 00 2e 48 00 00 00 02 85 09 a0 00 d3 01 00 00 <probe request starts here-> 40 00 00 00 ff ff ff ff ff ff e4 ce 8f 16 da 48 ff ff ff ff ff ff 80 4b 00 00 01 04 02 04 0b 16 ... >

Output:
{ headerRevision: 0,
  headerPad: 0,
  headerLength: 18,
  frequency: 64,
  strength: -1,
  antenna: 255,
  ieee802_11Frame: 
   { frameControl: 64,
     version: 0,
     type: 0,
     subType: 4,
     flags: 
      { raw: 0,
        moreFragments: false,
        isRetry: false,
        moreData: false,
        encrypted: false,
        ordered: false },
     duration: 0,
     bssid: 'ff:ff:ff:ff:ff:ff',
     shost: 'e4:ce:8f:16:da:48',
     dhost: 'ff:ff:ff:ff:ff:ff',
     fragSeq: 32843,
     beacon: undefined,
     llc: undefined,
     probe: { tags: [Object] } } }

**Comment by jmaxxz** [comment]
@fridaystreet will look into it. On my hardware everything is decoding correctly, but there could be a variable length field which is not being taken into account yet.

**Comment by fridaystreet** [comment]
@jmaxxz no worries thanks

**Comment by jmaxxz** [comment]
The header length is the source of the problem here. Of my hardware I get a header length of 26,  because your header length is 18 is not all the field I attempt to read can be present. Looking into the spec to see if I can figure out how what part of the header is suppose to be truncated when the length is not long enough for everything.

**Comment by jmaxxz** [comment]
Found it, the 2 bytes of flag data determine what fields will be present. Since this is not being parse the current implementation does will misread very often. I created issue #143 to track the progress of this fix.

**Comment by jmaxxz** [comment]
by my math the sample you provided does not include any signal strength information. Could you screenshot wireshark if it says differently?

**Comment by fridaystreet** [comment]
@jmaxxz yeah sorry I just posted up the buffer that node_pcap was creating showing it missing the extra 7 bytes. I'll get the full packet from wireshark for you as soon as I get home tonight.

Thanks
Paul

**Comment by jmaxxz** [comment]
@fridaystreet I maybe fine without it I just found the source of my problem, node 0.10.10 on osx does not properly support `readUInt32LE` updated to node 0.12 and I am back up and running.

**Comment by jmaxxz** [comment]
@fridaystreet nm found the issue wireshark should have been reporting a signalStrength of -45

**Pull request merged**
