### PR TITLE
[Node 4] Upgrade NAN to v2 and use Node 4 socketwatcher commit

### LINKED ISSUE #169: Installation failed with iojs v2.0.0
```
> socketwatcher@0.2.1 install /root/zpn-deploy/source/node_modules/pcappp/node_modules/pcap/node_modules/socketwatcher
> node-gyp rebuild

make: Entering directory `/root/zpn-deploy/source/node_modules/pcappp/node_modules/pcap/node_modules/socketwatcher/build'
  CXX(target) Release/obj.target/socketwatcher/socket_watcher.o
In file included from ../node_modules/nan/nan_new.h:190:0,
                 from ../node_modules/nan/nan.h:80,
                 from ../socket_watcher.hpp:8,
                 from ../socket_watcher.cpp:5:
../node_modules/nan/nan_implementation_12_inl.h: In static member function ‘static NanIntern::FactoryBase<v8::Signature>::return_t NanIntern::Factory<v8::Signature>::New(NanIntern::Factory<v8::Signature>::FTH, int, NanIntern::Factory<v8::Signature>::FTH*)’:
../node_modules/nan/nan_implementation_12_inl.h:181:76: error: no matching function for call to ‘v8::Signature::New(v8::Isolate*, NanIntern::Factory<v8::Signature>::FTH&, int&, NanIntern::Factory<v8::Signature>::FTH*&)’
   return v8::Signature::New(v8::Isolate::GetCurrent(), receiver, argc, argv);
                                                                            ^
../node_modules/nan/nan_implementation_12_inl.h:181:76: note: candidate is:
In file included from /root/.node-gyp/2.0.0/src/node.h:42:0,
                 from ../node_modules/nan/nan.h:24,
                 from ../socket_watcher.hpp:8,
                 from ../socket_watcher.cpp:5:
/root/.node-gyp/2.0.0/deps/v8/include/v8.h:4188:27: note: static v8::Local<v8::Signature> v8::Signature::New(v8::Isolate*, v8::Handle<v8::FunctionTemplate>)
   static Local<Signature> New(
                           ^
/root/.node-gyp/2.0.0/deps/v8/include/v8.h:4188:27: note:   candidate expects 2 arguments, 4 provided
make: *** [Release/obj.target/socketwatcher/socket_watcher.o] Error 1
make: Leaving directory `/root/zpn-deploy/source/node_modules/pcappp/node_modules/pcap/node_modules/socketwatcher/build'
gyp ERR! build error
```

Works find with iojs v1.8.1 :)

### LINKED ISSUE #181: Update to nan 2 for Node.js 4.0.0 compatibility.
Adding to the list: https://github.com/nodejs/node/issues/2798.
Related: #169.

### PR DESCRIPTION
**Pull request by ide**
Also update the engines field in package.json.

Fixes #181
Fixes #169

Test Plan: Ran a very basic test on OS X listening on `en0` (had to use sudo, which I believe is normal) and was able to pick up packets and see which MAC addr they were from.

### CODE REVIEW

**Comment by KenanSulayman** [comment]
Crap, I didn't see you already ported it. It was fun nevertheless (https://github.com/mranney/node_pcap/pull/184) :beers:  :+1:

**Comment by KenanSulayman** [comment]
The examples don't work here, either. We should look into that.. did the API differs from the examples on purpose and they simply weren't updated?

**Comment by ide** [comment]
I rebuilt node_pcap with Node 0.10.38 and had no luck running the examples either.

**Comment by KenanSulayman** [comment]
Alas :confused: However, it works just fine. So it doesn't really matter IMHO. A new set of examples could be delivered in a different PR.

**Comment by hortinstein** [comment]
I cannot figure out how to get this to build in node 4, is anyone else still having issues?

**Comment by KenanSulayman** [comment]
What OS, version, architecture?

**Comment by hortinstein** [comment]
disregard, i figured it out.  The new version was not pushed to NPM, so i just included a link directly to this repo

**Pull request merged**
