### PR TITLE
Port to NAN

### PR DESCRIPTION
**Pull request by zerouid**
Port to NAN - in case somebody is interested.

### CODE REVIEW

**Comment by mranney** [comment]
Hey @zerouid, this is awesome. Thanks for working on this. Sadly, this work collided with my refactor, and now it doesn't merge. Would you mind fixing it up so that it does? I didn't change the C++ much, so I don't think it'll be too bad.

**Comment by zerouid** [comment]
Hi @mranney, I'm glad if I could help. I did sync my branch with your latest, and resolved the conflicts. There are few things you should probably consider before you decide weather to merge or not. 
* The dependency "socketwatcher" needs to be ported too. I did that one too and I'm fetching it from my fork.
* When I tested after merging and got some errors from your new decoding routines:
```
node_pcap/decode/ipv6.js:63
    ret.payload_length = unpack.uint16(raw_packet, offset+4);
                         ^
ReferenceError: unpack is not defined
    at IPv6.decode
```
...am I missing something?

P.S. ...and BTW great job! Thanks!

**Comment by mranney** [comment]
You aren't missing anything, I just didn't finish the refactor on IPv6 and radio. But it looks like you went ahead and did that too.

I added you as a collaborator, so feel free to merge this if you are happy with it.

Hopefully soon someone will write some tests. :)

**Comment by mranney** [comment]
Oh, and also: nice work!

**Comment by mikeal** [comment]
This is awesome! Can we get it updated to `nan@1.5.0` or higher so that we can `io.js` support :)

**Pull request merged**
